### PR TITLE
Adding plugin to deploy bundles to Jahia server

### PR DESCRIPTION
**Pull request by josecarlosgt**

### CODE REVIEW

**Comment by jbarrera-xumak** [comment]
Hi @josecarlosgt I had thought on implement it in the same way as the profile to deploy to AEM instances, using the maven-sling-plugin:
For example:
```
        <profile>
            <id>deploy-jahia</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.sling</groupId>
                        <artifactId>maven-sling-plugin</artifactId>
                        <version>2.1.8</version>
                        <executions>
                            <execution>
                                <id>install-bundle</id>
                                <goals>
                                    <goal>install</goal>
                                </goals>
                                <configuration>
                                    <slingUrl>${jahia.slingURL}</slingUrl>
                                    <user>${jahia.username}</user>
                                    <password>${jahia.password}</password>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
```
I think in that way is more clean and we keep the same format as for AEM.

**Comment by josecarlosgt** [comment]
The plugin works fine. I have tested installing/uninstalling all dependencies and I did not find any issues. This PR updates installation procedures for API and CORE for Jahia.
The corresponding updates to the README sections in both API and CORE are in their respective repositories.

**Review by jbarrera-xumak — COMMENTED** [review]
I think  the variables for the deploy-jahia should be defined in the Pom too, so we do not have to edit our settings.xml to make it work.

**Comment by josecarlosgt** [comment]
OK. You mean add the properties currently in the settings to the properties section in the POM. I guess your point is to standardize installation of the DANTA dependencies across all platforms.

**Comment by jbarrera-xumak** [comment]
I mean add to the pom only the properties that were added with this new profile, the others are fine in the settings.xml. 
And just one more thing, could you please delete the repository plugin of jahia that was added in the first commit of this PR?

**Comment by josecarlosgt** [comment]
OK.

**Comment by jbarrera-xumak** [comment]
Fixes DantaFramework/API#10 and DantaFramework/Core#16

**Review by jbarrera-xumak — APPROVED** [review]
+1

**Pull request merged**
